INSERT INTO JOB(JOB_CODE,JOB_NAME,INSERT_DATE,INSERT_NAME)
VALUES ('JB001','SAL',SYSDATE,'LEE');

INSERT INTO JOB(JOB_CODE,JOB_NAME,INSERT_DATE,INSERT_NAME)
VALUES ('JB002','ORDER',SYSDATE,'kim');

INSERT INTO JOB(JOB_CODE,JOB_NAME,INSERT_DATE,INSERT_NAME)
VALUES ('JB003','MANAGER',SYSDATE,'park');

INSERT INTO JOB(JOB_CODE,JOB_NAME,INSERT_DATE,INSERT_NAME)
VALUES ('JB004','CASHER',SYSDATE,'shin');

INSERT INTO JOB(JOB_CODE,JOB_NAME,INSERT_DATE,INSERT_NAME)
VALUES ('JB005','SAMU',SYSDATE,'gu');