INSERT INTO STORE(STORE_CODE,STORE_NAME,STORE_PLACE,STORE_DATE,STORE_ONNER)
VALUES ('ST001','FISH','G-001',SYSDATE,'LEE');

INSERT INTO STORE(STORE_CODE,STORE_NAME,STORE_PLACE,STORE_DATE,STORE_ONNER)
VALUES ('ST002','TREE','G-002',SYSDATE,'kim');

INSERT INTO STORE(STORE_CODE,STORE_NAME,STORE_PLACE,STORE_DATE,STORE_ONNER)
VALUES ('ST003','GOGO','G-003',SYSDATE,'shin');

INSERT INTO STORE(STORE_CODE,STORE_NAME,STORE_PLACE,STORE_DATE,STORE_ONNER)
VALUES ('ST004','GAGA','G-004',SYSDATE,'do');

INSERT INTO STORE(STORE_CODE,STORE_NAME,STORE_PLACE,STORE_DATE,STORE_ONNER)
VALUES ('ST005','OIOI','G-005',SYSDATE,'dong');