INSERT INTO INOUTS(INOUT_NUMBER,INOUT,INOUT_DATE,INOUT_QUANTITY)
VALUES(INOUT_SEQ.NEXTVAL,'IN',SYSDATE,'1');

INSERT INTO INOUTS(INOUT_NUMBER,INOUT,INOUT_DATE,INOUT_QUANTITY)
VALUES(INOUT_SEQ.NEXTVAL,'IN',SYSDATE,'2');


INSERT INTO INOUTS(INOUT_NUMBER,STORE_CODE,PRODUCT_CODE,INOUT,INOUT_DATE,INOUT_QUANTITY)
VALUES(INOUT_SEQ.NEXTVAL,'ST001','SA0001','OUT',SYSDATE,'3');


INSERT INTO INOUTS(INOUT_NUMBER,INOUT,INOUT_DATE,INOUT_QUANTITY)
VALUES(INOUT_SEQ.NEXTVAL,'IN',SYSDATE,'4');


INSERT INTO INOUTS(INOUT_NUMBER,INOUT,INOUT_DATE,INOUT_QUANTITY)
VALUES(INOUT_SEQ.NEXTVAL,'OUT',SYSDATE,'5');


