CREATE SEQUENCE ORDER_SEQ
                START WITH 1 
                INCREMENT BY 1 
                MAXVALUE 100000 ;

CREATE SEQUENCE INOUT_SEQ
		START WITH 1
		INCREMENT BY 1
		MAXVALUE 300000 ;